[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Skipping tests in production build'"]

[start]
cmd = "sh -c 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'"
